### ISSUE TITLE
Website links query from Yigal for Dominik

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#28]
On July 8 2021, Yigal posed the following issues.  I'm putting them here for piecemeal processing.

> Dear Dominik,
> 
> I fully understand! Here are the issues. Whenever you have a minute.
> 
> Best,
> 
> Yigal
> 
> 
>     http://catalogues.indology.info/ was added for 4 different Print entities. Is this correct? Aren't there more specific links?
>     https://www.panditproject.org/entity/108794/print 
>     https://www.panditproject.org/entity/108255/print 
>     https://www.panditproject.org/entity/108001/print
>     https://www.panditproject.org/entity/108001/print
> 
> 
>     https://www.panditproject.org/entity/88926/work - Removed a broken link: A Śāradā MS of the NM - https://archive.org/details/NyayamanjariManuscript 
>     https://www.panditproject.org/entity/90939/work
>     Woolner Collection manuscript - Removed broken link: https://www.istb.univie.ac.at/cgi-bin/smwc/smwc.cgi?uid=default&browse_ms=311&browsed_field=86&nav=2&subnav=94
>     Move the scan links to a Print entity.
>     https://www.panditproject.org/entity/41478/work - Removed a broken link - E-edition at SARIT - http://sarit.indology.info/exist/apps/sarit/works/sarit__a%E1%B9%A3%E1%B9%AD%C4%81%E1%B9%85gah%E1%B9%9Bdayasa%E1%B9%83hit%C4%81
>     https://www.panditproject.org/entity/42131/work - Removed a broken link - Scan of MS Mysore ORI 5058 - https://archive.org/details/YogaratnavaliManuscriptMysore
>     https://www.panditproject.org/entity/105395/work - Removed a broken link - Panse 1955 at archive.org - http://n2t.net/ark:/13960/t7tn5ps82 
>     Sanskrit Medical Manuscripts in India - https://www.panditproject.org/entity/97284/print - Removed a broken link - http://wujastyk.net/mscats/Sanskrit_Catalogues/not%20in%20Biswas/Rama%20Rao%20Medical%20MSS%20in%20India/Rama-Rao_Sanskrit%20Medical%20Manuscripts%20In%20India_2006-smaller.pdf
>     https://www.panditproject.org/entity/101813/institution - the website link is broken.
>     https://www.panditproject.org/entity/102308/work - Shouldn't the resource be in the manuscript?
>     https://www.panditproject.org/entity/102254/institution - The link to the resources (represents the collection) should be added only to the collection, not to the institution.
>     https://www.panditproject.org/entity/108553/person - removed the following two links. They should have their entities.
>         https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3151383/ - G. Rohith Kumar and S. K. Rajesh 2010: a biographical article about his grandson
>         https://archive.org/details/AIADVolume11937/AIAD%20volume%202%201938/page/n183/mode/1up - the All India Ayurvedic Directory
>     https://www.panditproject.org/entity/108257/person - removed the following three links. They should have their entities with these links:
>         https://archive.org/details/AIADVolume11937/page/n39/mode/1up - biography in AIAD
>         https://archive.org/details/AIADVolume11937/page/n37/mode/1up - photo in AIAD
>         https://archive.org/stream/AIADVolume11937/AIAD%20volume%205%201949%20-%20illustrated%20pages%20in%20colour#page/n75/mode/1up - obituary in AIAD
>     https://www.panditproject.org/entity/108614/person - Dominik. Please enter the language name in "URL indispensable info."
> 
>

**Comment by wujastyk** [comment]
> http://catalogues.indology.info/ was added for 4 different Print entities. Is this correct? Aren't there more specific links?
> https://www.panditproject.org/entity/108794/print 
> https://www.panditproject.org/entity/108255/print 
> https://www.panditproject.org/entity/108001/print
> https://www.panditproject.org/entity/108001/print
> 

Okay, what's going on here is that in each case I am pointing to [http://catalogues.indology.info](http://catalogues.indology.info).  That site is one I built and maintain personally.  But the "back end" where all the files actually live, was my personal website, `http://wujastyk.net`.  I don't want to reveal that to the public, because it's personal and likely to change anyway.  In fact, I have now moved all the files to a different location, [http://nextcloud.computecanada.ca/index.php/s/M9QG8pDfzTZS9Jk](http://nextcloud.computecanada.ca/index.php/s/M9QG8pDfzTZS9Jk), where my university affiliation offers me some free space.  I may move the collection yet again, I'm not sure.  It's a lot of data and I need easy ways to update files etc.  The whole thing has reached the size and importance that it needs to be managed in a more professional manner.  

It would be great to have PURLs or DOIs for individual items, but that's just not possible at the present time.  So I only point to the top level URL. It's the best I can do at the present time.  The whole thing is quite well documented, so once a user arrives at the main catalogues.indology.info page, they should find their way pretty easily from there.

**Comment by wujastyk** [comment]
https://www.panditproject.org/entity/88926/work - Removed a broken link: A Śāradā MS of the NM - https://archive.org/details/NyayamanjariManuscript 

I don't understand.  You point to a work, https://www.panditproject.org/entity/88926/work .  Do you mean that there was a link to a MS here: https://www.panditproject.org/entity/97092/manuscript ?

**Comment by AmirSimantov** [comment]
> https://www.panditproject.org/entity/88926/work - Removed a broken link: A Śāradā MS of the NM - https://archive.org/details/NyayamanjariManuscript
> 
> I don't understand. You point to a work, https://www.panditproject.org/entity/88926/work . Do you mean that there was a link to a MS here: https://www.panditproject.org/entity/97092/manuscript ?

No, the link was on the reported Work entity.

**Comment by wujastyk** [comment]
I remain puzzled.  I see no URL in the 88926/work entry.  Oh, wait, you mean you already removed it?  Then it also needs to be removed from 97092/manuscript. 

Anyhow, this general issue is about link rot.  That scan of the Nyayamanjari MS used to be at Archive.org and then someone took it down.  The metadata for this can be retrieved from [this link at the Wayback machine](https://web.archive.org/web/20180415082248/https://archive.org/details/NyayamanjariManuscript), but apparently not the actual MS images.

If someone deletes the content of a URL that's been used in PP, there's not much we can do about it, except delete the PP link if we stumble across it.  There does exist link-checker software (like [WC3 link checker](https://validator.w3.org)) that crawls a site and reports dead links.  Maybe such a thing could be run for PP once a year or six months?

**Comment by AmirSimantov** [comment]
We aren't adding non-crucial behavior features at this point.
Is there anything we can do with the issue now, @wujastyk?
If not, let me know, and I will close it. Thanks.
