### ISSUE TITLE
Handling certain less popular scripts

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#33]
### Discussed in https://github.com/PanditProject/Website/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **chakrabortydeepro** July 25, 2021</sup>
@AmirSimantov I found that the project website cannot handle certain less popular scripts such as Grantha, Sharada. Newa or Tirhuta. Sometimes, we need to put titles in these scripts in the section "name in local script". But when these scripts in Unicode are used it gives the error message "The website encountered an unexpected error. Please try again later.". 

Is there any way to fix this problem?</div>

I thought of moving this here as it might serve a better purpose here. 

I think there should be immediate support for the following script:

1. [Brahmi](https://en.wikipedia.org/wiki/Brahmi_(Unicode_block))
2. [Kharoshthi](https://en.wikipedia.org/wiki/Kharoshthi_(Unicode_block))
3. [Sharada](https://en.wikipedia.org/wiki/Sharada_(Unicode_block))
4. [Grantha](https://en.wikipedia.org/wiki/Grantha_(Unicode_block))
5. [Newa](https://en.wikipedia.org/wiki/Newa_(Unicode_block))
6. [Tirhuta](https://en.wikipedia.org/wiki/Tirhuta_(Unicode_block))
7. [Nandinagari](https://en.wikipedia.org/wiki/Nandinagari_(Unicode_block))
8. [Siddham](https://en.wikipedia.org/wiki/Siddham_(Unicode_block))
9. [Vedic Extensions](https://en.wikipedia.org/wiki/Vedic_Extensions)
10. [Kaithi](https://en.wikipedia.org/wiki/Kaithi_(Unicode_block))
11. [Balinese](https://en.wikipedia.org/wiki/Balinese_(Unicode_block))
12. [Javanese](https://en.wikipedia.org/wiki/Javanese_(Unicode_block))
13. [Khudawadi](https://en.wikipedia.org/wiki/Khudawadi_(Unicode_block))
14. [Bhaiksuki](https://en.wikipedia.org/wiki/Bhaiksuki_(Unicode_block))

For the longer run, I think, a few other Indian scripts should also be included. Such as

1. [Sylhoti Nagari](https://en.wikipedia.org/wiki/Syloti_Nagri_(Unicode_block))
2. [Modi](https://en.wikipedia.org/wiki/Modi_(Unicode_block))
3. [Saurashtra](https://en.wikipedia.org/wiki/Saurashtra_(Unicode_block))
4. [Takri](https://en.wikipedia.org/wiki/Takri_(Unicode_block))
5. [Dogra](https://en.wikipedia.org/wiki/Dogra_(Unicode_block))
6. [Mahajani](https://en.wikipedia.org/wiki/Mahajani_(Unicode_block))
7. [Multani](https://en.wikipedia.org/wiki/Multani_(Unicode_block))

Maybe later these as well:

1. [Chakma](https://en.wikipedia.org/wiki/Kaithi_(Unicode_block))
2. [Meetei Mayek](https://en.wikipedia.org/wiki/Meetei_Mayek_(Unicode_block))
3. [Khojki](https://en.wikipedia.org/wiki/Khojki_(Unicode_block))
4. [Lepcha](https://en.wikipedia.org/wiki/Lepcha_(Unicode_block))
5. [Dives Akuru](https://en.wikipedia.org/wiki/Dives_Akuru_(Unicode_block))
6. [Limbu](https://en.wikipedia.org/wiki/Limbu_(Unicode_block))
7. [Sundanese](https://en.wikipedia.org/wiki/Sundanese_(Unicode_block))
8. [Cham](https://en.wikipedia.org/wiki/Cham_(Unicode_block))
9. [Gunjala Gondi](https://en.wikipedia.org/wiki/Gunjala_Gondi_(Unicode_block))

**Comment by AmirSimantov** [comment]
Hi @chakrabortydeepro, we currently don't have the resources to check whether each script works or not.
I advise that you tell me which script you have actually tried and the system doesn't present correctly.
We will check one script at a time.

**Comment by chakrabortydeepro** [comment]
@AmirSimantov I tried Grantha, Sharada and Tirhuta so far. They don't work. But if you want I can check which other ones don't work. I guess none of these work actually.

**Comment by AmirSimantov** [comment]
Thanks, Deepro. So will start with Grantha, Sharada, and Tirhuta :)
Could you please write down some names/words grouped by the script?
Thanks!

**Comment by chakrabortydeepro** [comment]
@AmirSimantov 
[Meghasandeśapradīpa](https://www.panditproject.org/entity/110011/work) in the regional script (Grantha) - 𑌮𑍇𑌘𑌸𑌨𑍍𑌦𑍇𑌶𑌪𑍍𑌰𑌦𑍀𑌪𑌃
[Tattvacintāmaṇyāloka](https://www.panditproject.org/entity/90652/work) in the regional script (Tirhuta) - 𑒞𑒞𑓂𑒞𑓂𑒫𑒔𑒱𑒢𑓂𑒞𑒰𑒧𑒝𑓂𑒨𑒰𑒪𑒼𑒏𑓁
[Bālabodhinī](https://www.panditproject.org/entity/108986/work) in the regional script (Sharada) - 𑆧𑆳𑆬𑆧𑆾𑆣𑆴𑆤𑆵
