### ISSUE TITLE
Adding "Assam" as a state

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#37]
I don't find Assam in the list of states. Could it be added?

**Comment by ybronner** [comment]
@chakrabortydeepro 
It is there, but it goes by Asom with Assam as an alternative name.
https://www.panditproject.org/entity/99225/state

**Comment by chakrabortydeepro** [comment]
Thanks, Prof. Bronner.

**Comment by wujastyk** [comment]
This raises a point I have been meaning to mention.  Searching for a name doesn't bring up the alternative names.  In the present case, searching for "Assam" should bring up the main entry, even though the "top" name is Asom.  But this issue applies to all names where there's an "alternative" field.
