### ISSUE TITLE
Retrive entities also by the "Alternative name" field - Reference field - Entity editing form

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#41]
branching from #37:

Searching for a place name doesn't bring up the alternative names.  For example, searching for "Assam" should bring up the main entry, even though the "top" name is Asom.  

This issue applies to some other situations where there's an "alternative" field.  I can't quite work out the behaviour.  For example, create a new work and enter "mooss" as the author; the popup offers N. S. Mooss but not Pulumanthole Sankaran Mooss (an alternate name).  But if you try "mus" you do get Pulumanthole Sankaran Mooss.  It's puzzling

**Comment by wujastyk** [comment]
Try to create a new site.

**Comment by AmirSimantov** [comment]
I cannot see the connection between my request to your sentence. Could you please elaborate? Would you please read and follow the instructions on how to report an issue? Thanks!

**Comment by wujastyk** [comment]
I'm very grateful!  This really helps!
