### ISSUE TITLE
Library of the Benares Sanskrit College

### ISSUE THREAD

**Issue by ybronner** [PanditProject/Website#43]
Is this library, which exists on Pandit  as an [institution](https://www.panditproject.org/entity/109296/institution), the same as the library of what is now called Sampurnanand Sanskrit [Vishwavidyalaya](https://en.wikipedia.org/wiki/Sampurnanand_Sanskrit_Vishwavidyalaya) (see also [here](http://www.ssvv.ac.in/))?
And if so, is the name "Library of the Benaras Sanskrit College" correct?

**Comment by wujastyk** [comment]
Yes, these: 
- Benares Sanskrit College
- Sanskrit College Benares ([PP](https://www.panditproject.org/entity/109426/institution))
- Government Sanskrit College, Varanasi
- Varanaseya Sanskrit Vishwavidyalaya
- Sampurnanand Sanskrit Vishwavidyalaya  (SSV)

are all the same place.  Well, except that the SSV is a huge umbrella organization and the old Benares Sanskrit College (est. 1791) is just a part of it now. 

I think it might be better to have the SSV entry as an institution. The library of the SSV is the [Sarasvati Bhavan Library](https://www.ssvv.ac.in/about-library) that has a [PP entry](https://www.panditproject.org/entity/40228/institution).

So the "Library of the Benares Sanskrit College" should be deleted and any links there reassigned to the SBL entry.

Will you do that, or shall I have a go?

**Comment by ybronner** [comment]
Many thanks! I made the changes myself.
