### ISSUE TITLE
No MSS display?

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#55]
When I bring up a work,[ e.g., the SS](https://panditproject.org/entity/42004/work), I don't see a list of MSS.  Am I doing something wrong?

**Comment by roikedem** [comment]
Thanks for this feedback, I will fix it and update here.
Issue number on my Jira: PAN-196

**Comment by roikedem** [comment]
I wrote also by mail to some of you:
This was fixed, you can see the manuscripts in the "Manuscripts" section of a work, if available.

Some elaboration regarding the gaps between the "old" Pandit and the new one: 
Pandit holds its data in a relational database, with fields which serve as "pointers" or references from one entity to another. One you look at an entity (a work in our case) with such pointers pointed at it from other entities (manuscripts in our case), we call it a "reverse" field of entity of type "work". In the migration work from old Pandit to new Pandit not all those reverse fields were properly imported. Furthermore, some of the pointers have their own metadata which complicates things more. 
As a conclusion, I would like to encourage you to keep looking for gaps and missing data and let me know.
