### ISSUE TITLE
Not saving edits

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#56]
I tried to edit a book entry: https://panditproject.org/node/96750/edit

I hit "save" but nothing happened and the edits were not saved.

**Comment by roikedem** [comment]
Hi, the problem most of the time is non-optional fields which are being
left blank. Until we fix this, first by exposing the error message which is
not visible right now, second, by not adding such empty fields.
In the case of the print you are trying to edit here, I guess the
problematic field is "State scholarship" which you have to remove to
overcome this problem. Again, this is until we fix it.

**Comment by roikedem** [comment]
Hi again,
The issue is resolved now, at least to the degree that I can see. Can you help me check that it is to your satisfaction?
What's been fixed: Required fields that are left blank trigger an error when you try to save the form.
