### ISSUE TITLE
Could not add manuscript entry

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#58]
Tried several times to add a manuscript entry. But it fails when I am going to publish it. Does not save the data entered. 
![image](https://github.com/user-attachments/assets/1f8a547c-6bce-41f3-ade6-cf925d197f75)

**Comment by wujastyk** [comment]
I have found the same.

**Comment by roikedem** [comment]
Thanks to you both, the issue has been resolved, please recheck it!
Thanks for your patience.

Roi
(Our issue: PAN-213

**Comment by chakrabortydeepro** [comment]
Thanks, Roi!
