### ISSUE TITLE
Extracts are not assigned to particular work

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#62]
- When I'm trying to add an extract it does not give me any option to select the particular work which the extract should be assigned to. 

- There are two dummy items as well. Should they be there?

- Previously there was a provision to add "facts" in which we could mention folio numbers, lines etc. I think this function should be added. 

![Screenshot from 2024-10-22 22-34-33](https://github.com/user-attachments/assets/2addc100-991c-4e8f-a085-981becac6212)

**Comment by roikedem** [comment]
Hi
Thanks for this bug report!
**It was fixed** (PAN-217) and you can re-edit your extract entities.

Regarding facts, did you mean this part of the form?
![image](https://github.com/user-attachments/assets/f459e557-34b5-42c7-a77a-2938d02d79c6)

(on the edit/add form, go to "publish" bulletin)
If you mean the specific fields related to folios and lines, they are in the manuscript entity edit/add forms, under the Physical section.
Please ask if this is not what you meant.

**Comment by chakrabortydeepro** [comment]
Thanks a lot, Roi. Yes, it works now. And I didn't see the options for facts in the "publish" bulletin. It is solved now. However, I have another issue related to the extracts. The extracts are shown under a "Work" item. However, they are not shown under the "manuscript" item. Extracts are taken from particular manuscripts. Therefore, they should be displaced under "manuscript" as well. For example, take the Work _Gurupustikā_: https://panditproject.org/node/114135
You can see that the extract appears in the "Work" column (although I think it should not be there— I had created an issue for it). However, if you go to its actual manuscript (https://panditproject.org/node/114141) you won't find the extract.

**Comment by ybronner** [comment]
Hi Deepro. You are right that extracts should be under manuscript, and they certainly shouldn't count as a work. I don't think you can now connect an extract to a work. I don't fully understand why this extract is connected to a work as a work. Roi, I think this is a bug that results from the import that we haven't noticed and that needs fixed. I checked other extracts (not thoroughly, though), and found that when you go from them to the work, you find them connected to that work as "works."

**Comment by roikedem** [comment]
"Extracts" section was added to manuscript display, I think it solves the problem, please check that it is as expected, @chakrabortydeepro @ybronner

**Comment by chakrabortydeepro** [comment]
@roikedem Thanks Roi! I can find extracts in the manuscript entries. However, the extracts are still listed under "Works" inside a Work entry. They should be listed under "Extracts" not under "Works." Here is an example from the [Bālabodhinī ](https://panditproject.org/entity/108986/work)entry:

![image](https://github.com/user-attachments/assets/bebefaf3-e72f-4d7f-a41a-c448de7e5293)

**Comment by roikedem** [comment]
@chakrabortydeepro 
Extracts moved to a section of their own.
thanks,
Roi

**Comment by chakrabortydeepro** [comment]
Thanks, Roi
