### ISSUE TITLE
Wrong options in "Influenced by"

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#64]
Wrong options are shown in the "influenced by" option. 
![image](https://github.com/user-attachments/assets/356085ab-ec6d-48ec-aed9-1402690c8b0a)

The options should be from "Persons" not Projects.

**Comment by roikedem** [comment]
Hi @chakrabortydeepro , thanks for this report, I fixed it (PAN-218)

**Comment by chakrabortydeepro** [comment]
Thanks, Roi.
