### ISSUE TITLE
New work not showing under its author

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#68]
I just added the [Madanādinighaṇṭu](https://panditproject.org/node/114162) by Candranandana.  But clicking on Candranandana does not include the Madanādi-  amongst his works.

**Comment by roikedem** [comment]
Hi @wujastyk , thanks for your feedback!

I think you might have missed the Madanadi- link -
This is the page of the work:
![image](https://github.com/user-attachments/assets/8d9d2ed8-ec38-4f7f-b7e2-65715e4b391e)
.
.
And this is the page of the author:

![image](https://github.com/user-attachments/assets/a038b40c-ec74-4b23-a1f6-e8ae00a2d5c5)

**Comment by wujastyk** [comment]
Thanks!  No, I didn't miss anything or make a mistake.  After adding the Madanādi- work, it did not show up under the entry for the author.  I refreshed the screen and re-selected the author entry several times.  But now the Madanādi-  does show up correctly.  There must be some time-lag or something.
