### ISSUE TITLE
No map view

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#71]
The previous version of the website included a map view of sites. It is not displayed in the new version.

**Comment by roikedem** [comment]
Dear @chakrabortydeepro ,
Thanks, this is on our tasks (PAN-60 for tracking)

**Comment by roikedem** [comment]
@chakrabortydeepro,
Today maps were added to Pandit

**Comment by chakrabortydeepro** [comment]
Thanks Roi
