### ISSUE TITLE
Work Entries ("the edition of") is displayed in Print Entries

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#73]
In the previous version, when a print entry served as an edition of a work it was shown on both the work entry and the print entry. Now print entries appear in work entries but not vice-versa. Here is an example:

[This print entry](https://panditproject.org/index.php/entity/66640/print) serves as an edition of [Ānandavardhinī](https://panditproject.org/index.php/entity/92533/work).

**Comment by roikedem** [comment]
Hi @chakrabortydeepro please check these entities now, I think it's ok.

**Comment by chakrabortydeepro** [comment]
Thanks Roi
